name: Syntax-checking

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare git
        run: git config --global core.autocrlf false

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: jsonlint
        uses: docker://github/super-linter:v3@sha256:6a7f8004183476af757b7559dc3b9ccd43989ec1b3a9fa8a75849bed23d07575
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSON: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
