name: Syntax-checking

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare git
        run: git config --global core.autocrlf false

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: jsonlint
        uses: docker://github/super-linter:v4@sha256:90bb745c4efd5e2d5266e18a6330a46a252a9e990f0d29a1c8ec0044ea79530d
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSON: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
